version: '3.8'

services:
  api:
    build: .
    container_name: api-container
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:YTVI1I8cvYXdoDJ2CDoAmXxlYfX47ogDTnIoawtrzHg=
      APP_URL: http://localhost
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: Projet_API
      DB_USERNAME: root
      DB_PASSWORD: password
    volumes:
      - .:/var/www
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Projet_API
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
